### STAGE 1: Build ###
FROM node:10.15.3 AS builder

RUN mkdir frontend
WORKDIR /frontend
COPY package*.json ./

RUN npm install
RUN mv ./node_modules ./

COPY . .

RUN npm run ng build

### STAGE 2: run ###

