# STAGE 1: BUILD
FROM node:10.15.3 AS builder

# RUN mkdir /frontend
WORKDIR /frontend
# ENV PATH /frontend/node_modules/.bin:$PATH
COPY package*.json /frontend/

RUN npm install
RUN npm install -g @angular/cli
COPY . .

RUN npm run build --prod --output-path=dist 

# STAGE 2: RUN
FROM node:10.15.3
RUN mkdir /app
# COPY --from=builder /frontend/dist/velociti-frontend /app
EXPOSE 4200
WORKDIR /app
CMD ["ng", "serve"]
